---
authors:
  - Jakob Meng (https://github.com/jm1)
dependencies:
  "jm1.ansible": '>=2022.10.23'
description: null
documentation: https://github.com/jm1/ansible-collection-jm1-pkg/tree/master/docs
homepage: https://github.com/jm1/ansible-collection-jm1-pkg
issues: https://github.com/jm1/ansible-collection-jm1-pkg/issues
#license: GPL-3.0-or-later
license_file: LICENSE.md
name: pkg
namespace: jm1
readme: README.md
repository: https://github.com/jm1/ansible-collection-jm1-pkg
tags: null
version: 2022.12.10
