---
authors:
  - Jakob Meng (https://github.com/jm1)
dependencies: {}
description: null
documentation: https://github.com/jm1/ansible-collection-pkg/tree/master/docs
homepage: https://github.com/jm1/ansible-collection-pkg
issues: https://github.com/jm1/ansible-collection-pkg/issues
#license: GPL-3.0-or-later
license_file: LICENSE.md
name: pkg
namespace: jm1
readme: README.md
repository: https://github.com/jm1/ansible-collection-pkg
tags: null
version: 2020.7.31
