galaxy_info:
  role_name: apt_repository
  author: Jakob Meng
  description: Manage apt keys and apt repositories
  company: Hochschule Bonn-Rhein-Sieg
  license: license (GPLv3)

  min_ansible_version: 2.9

  platforms:
  # Ref.: https://galaxy.ansible.com/api/v1/platforms/
  - name: Debian
    versions:
    - stretch
    - buster
    - bullseye
    - bookworm

  - name: Ubuntu
    versions:
    - bionic
    - focal
    - jammy

  galaxy_tags:
  - development
  - system

dependencies: []
