---
# Copyright (c) 2020 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Load variables to identify OS
  import_role:
    name: jm1.common # If Ansible raises "ERROR! the role 'jm1.common' was not found" then you might use the
                     # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

- name: Manage apt repositories
  loop: '{{ apt_repositories|default([]) }}'
  ansible.builtin.apt_repository:
    codename: '{{ item.codename|default(omit) }}'
    filename: '{{ item.filename|default(omit) }}'
    mode: '{{ item.mode|default(omit) }}'
    repo: '{{ item.repo|mandatory }}'
    state: '{{ item.state|default(omit) }}'
    update_cache: '{{ item.update_cache|default(omit) }}'
    update_cache_retries: '{{ item.update_cache_retries|default(omit) }}'
    update_cache_retry_max_delay: '{{ item.update_cache_retry_max_delay|default(omit) }}'
    validate_certs: '{{ item.validate_certs|default(omit) }}'
  register: apt_repository_result

- name: Debug role variables
  debug:
    msg:
      apt_repository_result: '{{ apt_repository_result }}'
  tags:
    - never
    - debug
