---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Manage apt repositories
  loop: '{{ apt_repositories|default([]) }}'
  ansible.builtin.apt_repository: '{{ item }}'
  register: apt_repository_result

- name: Debug role variables
  debug:
    msg:
      apt_repository_result: '{{ apt_repository_result }}'
  tags:
    - never
    - debug
