---
# Copyright (c) 2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Verify task definitions specified in apt_repository_config variable
  when: item is not mapping or (item.keys() | difference(['when'])) | list | length != 1
  ansible.builtin.fail:
    msg: >-
      Unsupported keyword or multiple module definitions found:
      {{ (item.keys() | difference(['when'])) | join(', ') }}.
  loop: '{{ apt_repository_config | default([]) }}'

- name: Ensure previous changes have been applied before changing apt repositories
  ansible.builtin.meta: flush_handlers

- name: Run tasks specified in apt_repository_config variable
  jm1.ansible.execute_module:
    name: "{{ (item.keys() | difference(['when'])) | first }}"
    args: "{{ item[(item.keys() | difference(['when'])) | first] }}"
    when: "{{ item['when'] | default(omit) }}"
  loop: "{{ apt_repository_config | default([]) }}"
  notify:
  - 'Update apt cache'

- name: Update apt cache now before subsequent tasks try to install packages
  ansible.builtin.meta: flush_handlers
