---
# Copyright (c) 2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Manage apt key
  loop: '{{ apt_repository_config|default([]) }}'
  when: "'apt_key' in item"
  ansible.builtin.apt_key: "{{ item['apt_key'] }}"
  register: apt_repository_config_apt_key_result

- name: Manage apt repository
  loop: '{{ apt_repository_config|default([]) }}'
  when: "'apt_repository' in item"
  ansible.builtin.apt_repository: "{{ item['apt_repository'] }}"
  register: apt_repository_config_apt_repository_result

- name: Change blocks in apt data source or apt key
  loop: '{{ apt_repository_config|default([]) }}'
  when: "'blockinfile' in item"
  ansible.builtin.blockinfile: "{{ item['blockinfile'] }}"
  register: apt_repository_config_blockinfile_result

- name: Copy apt data source or apt key
  loop: '{{ apt_repository_config|default([]) }}'
  when: "'copy' in item"
  ansible.builtin.copy: "{{ item['copy'] }}" # noqa risky-file-permissions
  register: apt_repository_config_copy_result

- name: Manage apt data source or apt key
  loop: '{{ apt_repository_config|default([]) }}'
  when: "'file' in item"
  ansible.builtin.file: "{{ item['file'] }}"
  register: apt_repository_config_file_result

- name: Change lines in apt data source or apt key
  loop: '{{ apt_repository_config|default([]) }}'
  when: "'lineinfile' in item"
  ansible.builtin.lineinfile: "{{ item['lineinfile'] }}"
  register: apt_repository_config_lineinfile_result

- name: Generate apt data source or apt key from template
  loop: '{{ apt_repository_config|default([]) }}'
  when: "'template' in item"
  ansible.builtin.template: "{{ item['template'] }}" # noqa risky-file-permissions
  register: apt_repository_config_template_result

- name: Debug role variables
  ansible.builtin.debug:
    msg:
      apt_repository_config_apt_key_result: '{{ apt_repository_config_apt_key_result }}'
      apt_repository_config_apt_repository_result: '{{ apt_repository_config_apt_repository_result }}'
      apt_repository_config_blockinfile_result: '{{ apt_repository_config_blockinfile_result }}'
      apt_repository_config_copy_result: '{{ apt_repository_config_copy_result }}'
      apt_repository_config_file_result: '{{ apt_repository_config_file_result }}'
      apt_repository_config_lineinfile_result: '{{ apt_repository_config_lineinfile_result }}'
      apt_repository_config_template_result: '{{ apt_repository_config_template_result }}'
  tags:
    - never
    - debug
