---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Load tasks specific to OS (fails if OS is unsupported)
  ansible.builtin.include_tasks: "{{ lookup('first_found',
                                            ['setup-' + distribution_id | join('-') + '.yml',
                                             'setup-' + distribution_id | first + '.yml']) }}"
