---
# Copyright (c) 2020-2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# NOTE: Synchronize changes with README.md

- name: Enable yum repositories for Extra Packages for Enterprise Linux (EPEL)
  ansible.builtin.import_role:
    name: jm1.pkg.yum_repository
  vars:
    yum_repository_config: '{{ yum_repository_config_epel }}'

- name: Install package dependencies for Red Hat Enterprise Linux 7 and CentOS 7
  ansible.builtin.package:
    name:
    # NOTE: Keep in sync with meta package below!
    - python-babel
    - python-backports
    - python-jinja2
    - python2-pip
    - rpm-build

- name: Install pip dependencies for Red Hat Enterprise Linux 7 and CentOS 7
  ansible.builtin.pip:
    name: backports.tempfile

- name: Install supplemental meta package
  jm1.pkg.meta_pkg:
    name: "jm1-pkg-setup"
    version: "3"
    depends:
    - python-babel
    - python-backports
    - python-jinja2
    - python2-pip
    - rpm-build
