---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# NOTE: Synchronize changes with README.md

- name: Satisfy requirements for collection jm1.pkg on Red Hat Enterprise Linux 7 and CentOS 7
  when: distribution_id|last == '7'
  block:

  - name: Enable yum repositories for Extra Packages for Enterprise Linux (EPEL)
    import_role:
      name: jm1.pkg.yum_repository
    vars:
      yum_repository_config: '{{ yum_repository_config_epel }}'

  - name: Install package dependencies for Red Hat Enterprise Linux 7 and CentOS 7
    package:
      name:
      # NOTE: Keep in sync with meta package below!
      - python-babel
      - python-backports
      - python-jinja2
      - python2-pip
      - rpm-build

  - name: Install pip dependencies for Red Hat Enterprise Linux 7 and CentOS 7
    block:
    - pip:
        name: backports.tempfile

  - name: Install supplemental meta package
    jm1.pkg.meta_pkg:
      name: "jm1-pkg-setup"
      version: "3"
      depends:
      - python-babel
      - python-backports
      - python-jinja2
      - python2-pip
      - rpm-build

- name: Satisfy requirements for collection jm1.pkg on Red Hat Enterprise Linux 8 and 9 and CentOS 8 and 9
  when: distribution_id|last in ['8', '9']
  block:
  - name: Install package dependencies for Red Hat Enterprise Linux 8 and 9 and CentOS 8 and 9
    package:
      name:
      # NOTE: Keep in sync with meta package below!
      - python3-babel
      - python3-dnf
      - python3-jinja2
      - rpm-build

  - name: Install supplemental meta package
    jm1.pkg.meta_pkg:
      name: "jm1-pkg-setup"
      version: "3"
      depends:
      - python3-babel
      - python3-dnf
      - python3-jinja2
      - rpm-build
