---
# NOTE: Synchronize changes with README.md

# Tasks for Debian and Ubuntu have been unified in a single file because of similarities between both distributions.

- name: Satisfy requirements for collection jm1.pkg on Debian 10 (Buster)
  when: distribution_id == ['Debian', '10']
  block:
  - name: Install package dependencies
    package:
      update_cache: yes
      cache_valid_time: 86400 # 1 day
      install_recommends: no
      name:
      # NOTE: Keep in sync with meta package below!
      - equivs
      - python-apt
      - python-backports.tempfile
      - python-jinja2
      - python3-apt
      - python3-jinja2

  - name: Install supplemental meta package
    jm1.pkg.meta_pkg:
      name: "jm1-pkg-setup"
      version: 2
      depends:
      - equivs
      - python-apt
      - python-jinja2
      - python-backports.tempfile
      - python3-apt
      - python3-jinja2

- name: >-
    Satisfy requirements for collection jm1.pkg on Ubuntu 20.04 LTS (Focal Fossa), Debian 11 (Bullseye) and
    Debian NA (Testing, Unstable aka Sid, Experimental)
  when: distribution_id in [
            ['Ubuntu', '20.04'],
            ['Debian', '11'],
            ['Debian', 'NA'],
            ['Debian', 'Testing'],
            ['Debian', 'Unstable']
        ]
  block:
  - name: Install package dependencies
    package:
      update_cache: yes
      cache_valid_time: 86400 # 1 day
      install_recommends: no
      name:
      # NOTE: Keep in sync with meta package below!
      - equivs
      - python3-apt
      - python3-jinja2

  - name: Install supplemental meta package
    jm1.pkg.meta_pkg:
      name: "jm1-pkg-setup"
      version: 2
      depends:
      - equivs
      - python3-apt
      - python3-jinja2
