---
# Copyright (c) 2020-2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# NOTE: Synchronize changes with README.md

# Tasks for Debian and Ubuntu have been unified in a single file because of similarities between both distributions.

- name: Install package dependencies
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400 # 1 day
    install_recommends: false
    name:
    # NOTE: Keep in sync with meta package below!
    - python3-apt
    - python3-jinja2

- name: Install supplemental meta package
  jm1.pkg.meta_pkg:
    name: "jm1-pkg-setup"
    version: "4"
    depends:
    - python3-apt
    - python3-jinja2
