---
# Copyright (c) 2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# NOTE: Synchronize changes with README.md

- name: Install package dependencies for Fedora
  ansible.builtin.package:
    name:
    # NOTE: Keep in sync with meta package below!
    - python3-babel
    - python3-dnf
    - python3-jinja2
    - rpm-build

- name: Install supplemental meta package
  jm1.pkg.meta_pkg:
    name: "jm1-pkg-setup"
    version: "3"
    depends:
    - python3-babel
    - python3-dnf
    - python3-jinja2
    - rpm-build
