---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# NOTE: Synchronize changes with README.md

# Tasks for Debian and Ubuntu have been unified in a single file because of similarities between both distributions.

- name: Satisfy requirements for collection jm1.pkg on Debian 10 (Buster) and Ubuntu 18.04 LTS (Bionic Beaver)
  when: distribution_id in [['Debian', '10'], ['Ubuntu', '18.04']]
  block:
  - name: Install package dependencies
    apt:
      update_cache: yes
      cache_valid_time: 86400 # 1 day
      install_recommends: no
      name:
      # NOTE: Keep in sync with meta package below!
      - python-apt
      - python-backports.tempfile
      - python-jinja2
      - python3-apt
      - python3-jinja2

  - name: Install supplemental meta package
    jm1.pkg.meta_pkg:
      name: "jm1-pkg-setup"
      version: "4"
      depends:
      - python-apt
      - python-jinja2
      - python-backports.tempfile
      - python3-apt
      - python3-jinja2

- name: >-
    Satisfy requirements for collection jm1.pkg on Ubuntu 20.04 LTS (Focal Fossa), Debian 11 (Bullseye) and
    Debian NA (Testing, Unstable aka Sid, Experimental)
  when: distribution_id in [
            ['Debian', '11'],
            ['Debian', '12'],
            ['Debian', 'NA'],
            ['Debian', 'Testing'],
            ['Debian', 'Unstable'],
            ['Ubuntu', '20.04']
        ]
  block:
  - name: Install package dependencies
    apt:
      update_cache: yes
      cache_valid_time: 86400 # 1 day
      install_recommends: no
      name:
      # NOTE: Keep in sync with meta package below!
      - python3-apt
      - python3-jinja2

  - name: Install supplemental meta package
    jm1.pkg.meta_pkg:
      name: "jm1-pkg-setup"
      version: "4"
      depends:
      - python3-apt
      - python3-jinja2
