---
# Copyright (c) 2020 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

apt_keys: |
  {{
    {
      'Debian_9': [
        apt_keys_debian.stretch_stable,
        apt_keys_debian.stretch_security_automatic,
        apt_keys_debian.stretch_automatic,
        apt_keys_debian.buster_stable,
        apt_keys_debian.buster_security_automatic,
        apt_keys_debian.buster_automatic,
        apt_keys_debian.bullseye_stable,
        apt_keys_debian.bullseye_security_automatic,
        apt_keys_debian.bullseye_automatic
      ],
      'Debian_10': [
        apt_keys_debian.stretch_stable,
        apt_keys_debian.stretch_security_automatic,
        apt_keys_debian.stretch_automatic,
        apt_keys_debian.buster_stable,
        apt_keys_debian.buster_security_automatic,
        apt_keys_debian.buster_automatic,
        apt_keys_debian.bullseye_stable,
        apt_keys_debian.bullseye_security_automatic,
        apt_keys_debian.bullseye_automatic
      ],
      'Debian_11': [
        apt_keys_debian.stretch_stable,
        apt_keys_debian.stretch_security_automatic,
        apt_keys_debian.stretch_automatic,
        apt_keys_debian.buster_stable,
        apt_keys_debian.buster_security_automatic,
        apt_keys_debian.buster_automatic,
        apt_keys_debian.bullseye_stable,
        apt_keys_debian.bullseye_security_automatic,
        apt_keys_debian.bullseye_automatic
      ],
      'Ubuntu_18_04': [
        apt_keys_ubuntu.ubuntu_2012_archive,
        apt_keys_ubuntu.ubuntu_2012_cdimage
      ],
      'Ubuntu_20_04': [
        apt_keys_ubuntu.ubuntu_2012_archive,
        apt_keys_ubuntu.ubuntu_2012_cdimage,
        apt_keys_ubuntu.ubuntu_2018_archive
      ]
    }[distribution_id|join('_')|regex_replace('[^A-Za-z0-9 _-]', '_')]
  }}

apt_keys_debian:
# Debian 9:  https://packages.debian.org/stretch/debian-archive-keyring
# Debian 10: https://packages.debian.org/buster/debian-archive-keyring
# Debian 11: https://packages.debian.org/bullseye/debian-archive-keyring
  stretch_stable:
    id: EF0F382A1A7B6500
    url: https://ftp-master.debian.org/keys/release-9.asc
    keyring: /etc/apt/trusted.gpg.d/debian-archive-stretch-stable.gpg

  stretch_security_automatic:
    id: EDA0D2388AE22BA9
    url: https://ftp-master.debian.org/keys/archive-key-9-security.asc
    keyring: /etc/apt/trusted.gpg.d/debian-archive-stretch-security-automatic.gpg

  stretch_automatic:
    id: E0B11894F66AEC98
    url: https://ftp-master.debian.org/keys/archive-key-9.asc
    keyring: /etc/apt/trusted.gpg.d/debian-archive-stretch-automatic.gpg

  buster_stable:
    id: DCC9EFBF77E11517
    url: https://ftp-master.debian.org/keys/release-10.asc
    keyring: /etc/apt/trusted.gpg.d/debian-archive-buster-stable.gpg

  buster_security_automatic:
    id: 4DFAB270CAA96DFA
    url: https://ftp-master.debian.org/keys/archive-key-10-security.asc
    keyring: /etc/apt/trusted.gpg.d/debian-archive-buster-security-automatic.gpg

  buster_automatic:
    id: DC30D7C23CBBABEE
    url: https://ftp-master.debian.org/keys/archive-key-10.asc
    keyring: /etc/apt/trusted.gpg.d/debian-archive-buster-automatic.gpg

  bullseye_stable:
    id: 605C66F00D6C9793
    url: https://ftp-master.debian.org/keys/release-11.asc
    keyring: /etc/apt/trusted.gpg.d/debian-archive-bullseye-stable.gpg

  bullseye_security_automatic:
    id: A48449044AAD5C5D
    url: https://ftp-master.debian.org/keys/archive-key-11-security.asc
    keyring: /etc/apt/trusted.gpg.d/debian-archive-bullseye-security-automatic.gpg

  bullseye_automatic:
    id: 73A4F27B8DD47936
    url: https://ftp-master.debian.org/keys/archive-key-11.asc
    keyring: /etc/apt/trusted.gpg.d/debian-archive-bullseye-automatic.gpg

apt_keys_ubuntu:
# Ubuntu 18.04: https://packages.ubuntu.com/bionic/ubuntu-keyring
# Ubuntu 20.04: https://packages.ubuntu.com/focal/ubuntu-keyring

  ubuntu_2012_archive:
    id: 3B4FE6ACC0B21F32
    keyring: /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-archive.gpg
    keyserver: keyserver.ubuntu.com

  ubuntu_2012_cdimage:
    id: D94AA3F0EFE21092
    keyring: /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg
    keyserver: keyserver.ubuntu.com

  ubuntu_2018_archive:
    id: 871920D1991BC93C
    keyring: /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg
    keyserver: keyserver.ubuntu.com

# Variable distribution_id is a list which uniquely identifies a distribution release, e.g.
#  [ 'CentOS', '8' ] for CentOS 8 (both Core and Stream)
#  [ 'Debian', '10' ] for Debian 10 (Buster)
#  [ 'Debian', 'Unstable' ] for Debian Unstable (Sid)
#  [ 'Red Hat Enterprise Linux', '8' ]` for Red Hat Enterprise Linux (RHEL) 8
#  [ 'Ubuntu', '20.04' ] for Ubuntu 20.04 LTS (Focal Fossa)
distribution_id:
- '{{ ansible_facts.distribution }}'
- # Use major and minor version for Ubuntu, e.g. Ubuntu 18.04 LTS (Bionic Beaver) or Ubuntu 20.04 LTS (Focal Fossa).
  # Use major version in title case for unknown Debian releases, i.e. the major version is not a number and not 'NA',
  # e.g. when VERSION_ID is not set in /etc/os-release and lsb_release is available on that host, then
  # ansible_facts.distribution_major_version is defined as 'testing' which will be converted to 'Testing'.
  # Use major version for all other distributions, e.g. CentOS 7, Debian 10 (Buster) or Red Hat Enterprise Linux 8.
  "{{ ansible_facts.distribution_version if ansible_facts.distribution == 'Ubuntu' else
      ansible_facts.distribution_major_version|title if
        ansible_facts.distribution == 'Debian' and
        ansible_facts.distribution_major_version is not number and
        ansible_facts.distribution_major_version != 'NA' else
          ansible_facts.distribution_major_version }}"
