---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Manage apt keys
  loop: '{{ apt_keys|default([]) }}'
  ansible.builtin.apt_key:
    data: '{{ item.data|default(omit) }}'
    file: '{{ item.file|default(omit) }}'
    id: '{{ item.id|default(omit) }}'
    keyring: '{{ item.keyring|default(omit) }}'
    keyserver: '{{ item.keyserver|default(omit) }}'
    state: '{{ item.state|default(omit) }}'
    url: '{{ item.url|default(omit) }}'
    validate_certs: '{{ item.validate_certs|default(omit) }}'
  register: apt_keys_result

- name: Debug role variables
  debug:
    msg:
      apt_keys_result: '{{ apt_keys_result }}'
  tags:
    - never
    - debug
