---
# Copyright (c) 2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# Variable distribution_id is a list which uniquely identifies a distribution release, e.g.
#  [ 'CentOS', '8' ] for CentOS 8 (both Core and Stream)
#  [ 'Debian', '10' ] for Debian 10 (Buster)
#  [ 'Debian', 'Unstable' ] for Debian Unstable (Sid)
#  [ 'Red Hat Enterprise Linux', '8' ]` for Red Hat Enterprise Linux (RHEL) 8
#  [ 'Ubuntu', '20.04' ] for Ubuntu 20.04 LTS (Focal Fossa)
distribution_id:
- '{{ ansible_facts.distribution }}'
- # Use major and minor version for Ubuntu, e.g. Ubuntu 18.04 LTS (Bionic Beaver) or Ubuntu 20.04 LTS (Focal Fossa).
  # Use major version in title case for unknown Debian releases, i.e. the major version is not a number and not 'NA',
  # e.g. when VERSION_ID is not set in /etc/os-release and lsb_release is available on that host, then
  # ansible_facts.distribution_major_version is defined as 'testing' which will be converted to 'Testing'.
  # Use major version for all other distributions, e.g. CentOS 7, Debian 10 (Buster) or Red Hat Enterprise Linux 8.
  "{{ ansible_facts.distribution_version if ansible_facts.distribution == 'Ubuntu' else
      ansible_facts.distribution_major_version | title if
        ansible_facts.distribution == 'Debian' and
        ansible_facts.distribution_major_version is not number and
        ansible_facts.distribution_major_version != 'NA' else
          ansible_facts.distribution_major_version }}"

yum_repository_config: '{{ yum_repository_config_epel }}'

yum_repository_config_centos_7:
  # Extra Packages for Enterprise Linux (EPEL)
  # Ref.: https://docs.fedoraproject.org/en-US/epel/
  epel:
  - ansible.builtin.yum:
      name: epel-release

yum_repository_config_centos_8:
  # Extra Packages for Enterprise Linux (EPEL)
  # Ref.: https://docs.fedoraproject.org/en-US/epel/
  epel:
  - ansible.builtin.dnf:
      name: epel-release
  epel_next:
  - ansible.builtin.dnf:
      name: epel-next-release

yum_repository_config_centos_9:
  # Extra Packages for Enterprise Linux (EPEL)
  # Ref.: https://docs.fedoraproject.org/en-US/epel/
  epel:
  - ansible.builtin.dnf:
      disable_gpg_check: yes
      name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ distribution_id | last }}.noarch.rpm'
  epel_next:
  - ansible.builtin.dnf:
      disable_gpg_check: yes
      name: 'https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-{{ distribution_id | last }}.noarch.rpm'

# Extra Packages for Enterprise Linux (EPEL)
# Ref.: https://docs.fedoraproject.org/en-US/epel/
#
# Distinction between Stream and Core in distribution_release since Ansible 2.11
# Ref.: https://github.com/ansible/ansible/commit/7f0eb7ad799e531a8fbe5cc4f46046a4b1aeb093
yum_repository_config_epel: |
  {{
    {
      'CentOS_7': yum_repository_config_centos_7.epel,
      'CentOS_8': yum_repository_config_centos_8.epel,
      'CentOS_9': yum_repository_config_centos_9.epel,
      'Red_Hat_Enterprise_Linux_7': yum_repository_config_red_hat_enterprise_linux_7.epel,
      'Red_Hat_Enterprise_Linux_8': yum_repository_config_red_hat_enterprise_linux_8.epel,
      'Red_Hat_Enterprise_Linux_9': yum_repository_config_red_hat_enterprise_linux_9.epel
    }[distribution_id | join('_') | regex_replace('[^A-Za-z0-9 _-]', '_')] +
    {
      'CentOS_8_Stream': yum_repository_config_centos_8.epel_next,
      'CentOS_9_Stream': yum_repository_config_centos_9.epel_next,
    }[
      (distribution_id+[ansible_facts.distribution_release]) | join('_') | regex_replace('[^A-Za-z0-9 _-]', '_')
    ] | default([])
  }}

yum_repository_config_red_hat_enterprise_linux_7:
  # Extra Packages for Enterprise Linux (EPEL)
  # Ref.: https://docs.fedoraproject.org/en-US/epel/
  epel:
  - ansible.builtin.yum:
      disable_gpg_check: yes
      name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ distribution_id | last }}.noarch.rpm'

yum_repository_config_red_hat_enterprise_linux_8: '{{ yum_repository_config_red_hat_enterprise_linux_7 }}'

yum_repository_config_red_hat_enterprise_linux_9: '{{ yum_repository_config_red_hat_enterprise_linux_7 }}'
